force-app/main/default/objects/Alquiler_de_vehiculo__c/Alquiler_de_vehiculo__c.object-meta.xml
<CustomObject>
    <label>Alquiler de vehiculo</label>
    <nameField>
        <label>Alquiler de vehiculo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alquiler de vehiculos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alquiler_de_vehiculo__c/fields/Catindad_de_Vehiculos__c.field-meta.xml
<CustomField>
    <fullName>Catindad_de_Vehiculos__c</fullName>
    <label>Catindad de Vehiculos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Alquiler_de_vehiculo__c/fields/Vehiculo_de_Carga__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo_de_Carga__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehiculo de Carga</label>
    <referenceTo>Vehiculo_de_Carga__c</referenceTo>
    <relationshipLabel>Alquiler de vehiculos</relationshipLabel>
    <relationshipName>Alquiler_de_vehiculos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehiculo_de_Carga__c/Vehiculo_de_Carga__c.object-meta.xml
<CustomObject>
    <label>Vehiculo de Carga</label>
    <nameField>
        <label>Vehiculo de Carga Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehiculos de Cargas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo_de_Carga__c/fields/Cantidad_de_Flota__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Flota__c</fullName>
    <label>Cantidad de Flota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AlquilerScheduler.cls
global  class AlquilerScheduler  implements Schedulable  {
 
    global void execute(SchedulableContext ctx) {

    List<Alquiler_de_vehiculo__c> listaVe = new List<Alquiler_de_vehiculo__c>();
    List<Vehiculo_de_Carga__c> lf = new List<Vehiculo_de_Carga__c>();
   

    

    for (Alquiler_de_vehiculo__c alqu : [SELECT
                                                Fecha_Final__c,
                                                Vehiculo_de_Carga__r.Name,
                                                Catindad_de_Vehiculos__c,
                                                Vehiculo_de_Carga__r.id
                                                From Alquiler_de_vehiculo__c where Fecha_Final__c = TODAY ]) {
                    
                                                    Vehiculo_de_Carga__c ver = new Vehiculo_de_Carga__c();
                                                    ver.Cantidad_de_Flota__c = alqu.Catindad_de_Vehiculos__c;
       }
      
       System.debug(listaVe);
       

    }

}