force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <label>Vehiculo</label>
    <nameField>
        <label>Vehiculo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehiculo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Viajes_individuales__c/Viajes_individuales__c.object-meta.xml
<CustomObject>
    <label>Viajes individuales</label>
    <nameField>
        <label>Viajes individuales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viajes individuales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Viajes_individuales__c/fields/Vehiculo__c.field-meta.xml
<CustomField>
    <fullName>Vehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehiculo</label>
    <referenceTo>Vehiculo__c</referenceTo>
    <relationshipLabel>Viajes individuales</relationshipLabel>
    <relationshipName>Viajes_individuales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ViajesIndividuales.cls
global class ViajesIndividuales {
  
     public static void UpdateVehiculos(){
    List<Viajes_individuales__c> lista = new List<Viajes_individuales__c>();
    List<Vehiculo__c> listv = new List<Vehiculo__c>();
    System.debug('hola');
    for (Viajes_individuales__c alquiler : [SELECT 
    Id,
    Vehiculo__r.Id,
    Vehiculo__r.name,
    Vehiculo__r.Estado__c
    From Viajes_individuales__c
    where Fecha_Final__c = TODAY ]) {
    
    Vehiculo__c vahiculo = new Vehiculo__c();
    vahiculo.Id= alquiler.Vehiculo__r.Id;
    vahiculo.Estado__c =true;
    listv.add(vahiculo);
   

        
  }  

  System.debug( listv);

  update listv;
 }
}